---
language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -qg bower grunt-cli
- npm install -q
- bower install --force
- bower install --force
after_success:
- "./node_modules/angular-ui-publisher/travis/authentication.sh || exit 0"
- "grunt dist build:gh-pages publish:gh-pages build:bower publish:bower"
script: grunt
env:
  global:
  - MAIN_BRANCH=develop
  - REPO="git@github.com:douglasduteil/ui-ace.git"
  - secure: ! 'ZtniRsuA62L1+WQiP6VRMgQTsSseQlShdM4L7+TqBtJ40uPxptYvWlhUM2s0

      7oJsBzvqh6aN2zISkm0/yYQQHx5JXwwOljvdYGWybTOy4X00Z5rpWmWh1Zg8

      Ot9HquFexahv94cBB9BetvOkcW0Z9Jq/pY2C24VJ/KhtYr0qXyM='
  - secure: ! 'RDgIiQHxchhVUT31PTy3G7spm/uM0pOr58MFSom1eiP3XEA51Q1rwhuSu43S

      FuwL7eSJvRiz59MI/lmp/mm19ls9v8sRC80UGfde5T3kisMDfAIwpaXO+0an

      2Zis1L2VTTsH6nW6l+sPABwPelEp91TSu4WYxiTIWAY5OF/7E8s='
  - secure: ! 'POskmn+bXO8LSVTvFvVb2yef6QiawS+oFD22FKzX0cdGEHtwm7li0ddY8YfW

      8+gZY+h3FDbt4RgE1EMF/pBhQgNOmEB8e+TlQx3noY+pBHWgEaMVVb0cFbfK

      kvubtB0Zxfck9027szTVj6VfAZOvpFFL7LvHLlOoK+dVbt13zlw='
  - secure: ! 'UGVNOsyhw0gbTGtjfxHX0YxHRMr3DCUfpArzd+AjH+LK1ivsPoAlFz5XCw4x

      ftrGmx4Anb/ZS1HqJc+eyYv6xuyHJCNfyDOUSBAK3IJBYgtN2QKNJDi0HSgY

      Cidu3/2ynXJ0RhzwfVQOxZbP/tP21bzIsYVqN8N5Q7Dhw8n4RaM='
  - secure: ! 'fwWbr13F7qHXGWgiPdAtO51kNP4Ls9kqIZPVSEeBoDiymBtYGSbp1XdD56gj

      ye3sCPWePFOl/mR29k4k0k5DLo4hY2I5j/iilf3uVe2FSagvoStXTENVTx+z

      w2163cEAX1CET2Xg87zwkTgXBXqdfLb2AnyIX9eHlMavjI2rHRE='
  - secure: ! 'RcfC9p5lYidrRLeV+q/QxVAskRPbrWX12jVIpZkk04DpNQhAwHEL5mv5NBgr

      B5aX7f73ozPpsDPD/698EtXcqUFA6PUCp47uKNw+XfpLFKLQj97EbCGTo7z2

      CDcr3U0IcnE3+FEafIv46xhCqTY10q6HZvH6wHbScxUme0k4Lvs='
  - secure: ! 'IZ73NjMqjeZ3hnd7of8ntd0YiMI3OWZmpaPFMzMY5T4QZS+UNRu9uTmbl2Go

      Yf4VSiCoOgNupeK4wZkZhvITYvrKsMiCVO4wJkqoauUOjHjazvCvEJpg4pgC

      oVSXVnBaKGYXEYkk+6sGXc4UU8+KnBqOPYKRq7I+tYRDaMP/2sI='
  - secure: ! 'S2e6joXt4sohLq2HVFsNRJ2BgTSTgYDzNFtpHcUeS2TSU8rh1BtkVzXuEJ75

      MbNkGiD93+EeI68wSQQIkb8/EvH4BQQxnXcb4coeSWyguXfktn3BsZjFQCPI

      33DXJuv8YKQtIpoA6ISc+jXGzk/STXQShB2XsCC/uMklUE0sNLs='
  - secure: ! 'bcN7nbRciJzp7WTNjOelGDREoRtMmX9QQiKVwkHrXrL516jFD83kGVlq2wIG

      YBxbTroLUjZbj7/khkcmFX/B6ILTz2Sh1gMpNhwv6jchJQkmLNGSrslII3YI

      gccNBqOEiTIPKO3lt/9QKlqx2x7gLE0UuFZ3mGu4rv9CqxaD4Yo='
  - secure: ! 'LZpgNF1F5fpZUoDaGHhs7KtFjZiE3kZbWTroq2K1QpWPGgfp1Lw8cHL2a/GI

      HJRuEwy0f6VceB7XvcyUnH/bvj6LH+UE2ep5pMGZAIzbopUElHsQr7JTCi3O

      +966pM0EVBMUiZloN6l0EdZ5sNOK9a4TmuA7XxyYkHnO6fufc9I='
  - secure: ! 'KJwc5H+vjqVtW1ozmteSOCOMYs+meLrX7GOzmZuRaoYoQgmzXycRWszjW/4l

      BfZ0tGQE3djX82k6bJBMbJrQ7LZJAkXTMPIh9Yxnbj7/RsMcW3rvX1L8ysUC

      5m5bJc7HuilR2S3bM5SZY6oHz8Uu2fCezqH3C12+TsfSR+yZJdA='
  - secure: ! 'SOpUW461LcRwUMXRSn1cM2j+jzyZGIBDrQLTvUP0mU9FBuKU3KQUZpS4QzIg

      y7+alB/vuvoQ7GHOjo5i5Usg/WZFLZ3eVHQzLuzRoPdH23p5IKExiAxUCv76

      DA0AObC9abXGihtGkxr4ka5K76TcG8bFr96OFO6KsxGqPa0i5yY='
  - secure: ! 'IspsyAQtBVgutlpJxopcJ11q1GDmzENBwU4QcdxsHHrt6NRAEDaYmsUyTGzh

      5tDxM7x6n4DF77H0RKMynjaZlZFrFhbZDqI5W4gDdGEEsp5cOBRL1D67W9k4

      o8n+m3wB6lcsdk4Pl45ODI2U6nSJ2Izsou2NVHux5jZPN75JTYc='
  - secure: ! 'j8Go+J5F7ExuGMAaTUeh/7C1RWKv3EHFzTnbQByR/fxVMfpMPw8QEyQ6bWjI

      Zl1TG9PUsaCoLX4Lnp1grsAExdrvsLeItdlUmbXZfcmdVlkDTQ5wsyEUwQr6

      /KHSE4I3PxbQUrgo5u59OH/7Dk3xDl6h906Ec2NeGOXG1LyrvOE='
  - secure: ! 'LLieSKGfiKC0z7Ag8pkdO/BP/9wt9bAHRNSa2uwdu3l7iXZAGWr8WAqSfxM7

      L9wXfbgszh8EmQsJX9B/YqClmf2qLS/4LatlQSe3Ba9zrD71x+3qZXaB7KK9

      Djzb3ybQdJnOCHVkaWPFEBSbYFUvDsMEmEjoigeK0jEE0cnlrSs='
  - secure: ! 'Ee0QN7ezBbuWHya5g0lwwEEpmmZFO2SvT5TEAXAYBAFSOfSTKmOQ90KiB6nA

      vFPnfRag4lWuFfjpBQ1KE3VwrFBaQRNYrI/YcN0BeeG9kqbEDhxZMvQG5WrO

      v+whAT9ROFO+PnVHY3bCbLW7f8lAPj0aLOTedWwVyzUhTh1sKAU='
  - secure: ! 'QrsxS4K7XcrxGSzJsrGRtCCZ1R1zCtgk5WXbJItlL5lVmb6m8HszVucK6ehJ

      CIabrVtGVJzd4lxAzEiTvdLCXgf8CFV2wjIGWH0Wxf4lUw2ZgMdbIizErdRG

      WL0qxEHqGjxm0IjnIWIlP7OmaFekrZcgP3OZ5ARpT4b70YGz4Ok='
  - secure: ! 'UWxqoLyj+ylWrToe8NkESh58WLo2IJxkSm4zrULBMj+pz4MEv/woyeoc5OlD

      0uKdonpyZmJtkxRRlqgdwdfeGdOrGvHFjxxc2I+qqp1px6ImIN6WKgQh/PBh

      /PHfq+pGkRCP5IK52DGcGP0WPOA58GYpNEsa3TFSpbdKcMGbK/c='
  - secure: ! 'VQb2Gt0iVMKNkPFZmV8pT8T/MAsAKqC+l9+RY537Za6goH3gTfZUKErYWVKa

      1NyhlFq/JEdA8rXetBCaxLwoEybASE7ancKj/d46KHpNVcfuFRK0fiPJr1R3

      dyzv33DDpntgatPVawdBXAWooFtfNH8N1zqNQSHEuTFigUGXC/4='
  - secure: ! 'JXqgm6fPlSQGlhgAnhdRya/GJcsL4R9LzG7n8zwZvFUs9/7YfJFEjbkvY+zD

      Eq8E8Y8M43BoXGod9OxmJ6zMfnBHADBoOSwlOxWB79RYwHj221kY5DgRV/Fx

      /yJC49g7C/Exqf/nb6d/QfXf0c6DxX4Nz1bPoLZpf+ESUzVrBFM='
  - secure: ! 'AxhY9P1R2LUzin20Z2eR3PfPeBzcYLUdgHSWFSqtjjU/tni089tlemegqd9+

      P12eTqtZrTaLbqBrmqvqLtjJigT6fgT5M+4aFvocvi77EUwyrATG0Why2ml3

      UTXH+SvoI2FGjutlXhn603iSklUxStneeT8ZfLM9bF8/LJ7QmSg='
  - secure: ! 'GAFLsLpmrgJSaWRWT96blTQFA6QIDoQEiu1UVtHJF/ee6n0/6x6yQUSaNnPP

      Q1y4SdyVgzWUR1jdmb2FzMvohhYjYoX0+ArUo8PpGLV1xl0sCst3lUNXUl8Z

      rai1YxQZwH+yY0ZrJ7NZWhMaRgUBK7Jvi657A03NJo0aKq1SBa4='
  - secure: ! 'Rz97eIVx3WoKr2O3deBErjtBoBbMbJtwNNJzzEUcMp6CHdWkTr15Ibxwk4mT

      AHEn2gcQXQcWushQlL4GWDeU8287KjvJylNQHyrYYsM3O2pJctUnSv+8tGQX

      U5TWVQsftt/tqvQSDtvjk3bL7RoEXmq2WslnIjDsMS1zWeaBT9A='
