---
language: node_js
node_js:
- '0.8'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g bower grunt-cli
- npm install
- bower install
before_script: out/.travis/before_script.sh
after_success: out/.travis/after_success.sh
branches:
  only:
  - ft-doc-t0
script: grunt
env:
  global:
  - REPO="git@github.com:douglasduteil/ui-ace.git"
  - secure: ! 'undvAI7JYMz1Qyjz+137POY/aO3II2GKV1sFJmPyrIFp6un32A0qwDPKqq66

      /C3aIQkraFCVyileiZtymmNjGvnbvu0j4o84TYN5b1/uqN/Kf6DMsfvVqa5M

      YCpWxNowifQDdegHKz/OjbyxbQpmt4nqrawTKDfT3WC8BlM87LI='
  - secure: ! 'HjoZqkASAH4P9kFpSbvPVtY5RlJsvzzEk+vdw10qmoyfGY46L/bx7ZyENSRJ

      47On8bxC1ml8Oyrgld1uwvn1vYx1r/0Yn9EKBaqbecNRN7uKvbx7Y+N0bjZD

      kjSQeag82aTy7fnhgDsM8chrAyZvgYpPjHMgAPcvFMBRqbFlu/k='
  - secure: ! 'uEC1bqx8jNQyS5mkaIyOCkDIKBvoIwPiGlopcjrQgqL/nOWk25/gIULtVCgs

      r1dtAk3sM11ftKe3SjFcD80hrAhgDOtW/ur3XCZkxKKOQkhTIFnu4nf2Kak9

      Cx7as3Z1oy9w6ZxUVHtuMiD5VdxK8wW5Bq0JsXOn2KDrcTqGi5c='
  - secure: ! 'UmfsX7OvTnJIzzjdaf2oJJKk7/S5jenVR1iKE6h92SKao4B1VOyp1r++h5CE

      gLw7r+MTe1JmFy7D326yOH6C6RY0iMlkU7s0Qoe+QmkfjY0P8K7p3aLNPUVh

      YvSP7a6FBK9GPIPvGZq84M4rVnXQMqGItidsRXShiZH3pqttSuA='
  - secure: ! 'FgiHld/aGT7/Fo+fkVW8KqY/hBqxa1+5hGgk5vPFYs+EPWyBCrvLHIdKEHH6

      eOfjU8jt7SuhAibglVZbdjZwojgrq/nTYb6a5g2G3eZY0AuJRjLBaGDa8moS

      jiZiF91KeirllGqbukq3i/IzSV8zoeLC1EvaJoY8E7IpVXHZzEs='
  - secure: ! 'jUwQNUaXP+BR6VPd/mKbLLBdZHutH2lxICLcfYTu5wYpOx9CTeeDgV1tx039

      ERNwJPlmZZnzVO2PU6/SZJlJ2OO2yUSxX+PCdQ8rbYD4K1abea74CqwKGwXn

      yygWv5YA5syYTaLDaBcP7Zo9wglkl9Ts6AdLZAPx1whZ6vwlkoo='
  - secure: ! 'lfxFrDsKrxHQBh+qg3WoZa8LtGqYi+A8V1SwUC9t7y8fFpZvpdTuWjUpPyx0

      QQ/UChShQ6hVe7LoYYrYUXxkLZ8gqXFFx1Krhg+QjS9aP2MGswdVqMXsndrN

      r+DY5Ka4wYTThiOnVd3X+bA6yho1fCKu/jwBwyTZUey1SIjeTOw='
  - secure: ! 'Jj3OI4/v4ukEhkSjomhfsKXOK/KraU1bwI/uCcoAOhRt0BugWu9IKcXlR1AE

      sQBvdYFhPNpa/kKmB7UsxzBlVMntplrht7FpUiXfvQbdOSdmBqlPuq+tUBxm

      Tg+F+skmhEJ7fX16I8YvuLffIZXGJbHqk27qLajNMiu9ZSu0Dgc='
  - secure: ! 'kcXO04c19G4jRN7Ws3TxQP1SsJJcz7g7kqSbGNDqXaY/byAQaAgM0oUq9MrQ

      0aKdcVRG+zhjymq/3WgbrlR7R49V3ztwmHPJB3ioUED1tHGJbFwouZbHDBQ5

      hbMV/g97XZXvrOmcwj1BicViubsIw2peidscYA7E/Rs4g+zL908='
  - secure: ! 'Dg6BMUtV2NEE1vQdkstfoC9N0A3ApLUzh/92cdXmKESHQPwgDFDnMtLkCbI3

      QJ+Yg70JT/7DwKBR3XHMnMOICaplDzUKYy5Z54YTB1iQgUDNIEYj0crQOz6Q

      /eSxSkxCv3/pzghky9tq9+NDXT/M4Sbq5mqC7eRhtGkZ1BA2N88='
  - secure: ! 'BJrEYYO3NayNh4Vud1hmAcZN7rX6v/J8/IFQCBV5YAvmWti9pwn2jbnZaTM7

      WmSNTri/EoSSkNqovvYYLhopgJHu3rW9p2SqdLjmxPrVHEDUsIBoubhDOtQR

      8IpBGe2skNEQihgUWEyWQxa9pk6jzMBhz2kdJBOKFJHK3Rs7b/w='
  - secure: ! 'j71MzUlEOq9c5vkbTtbpUbzjZmWPA1+g365wOORy596vuMux0Fohr6qFZJ0t

      Ky0iMjmoBTdSRjvR0WWcA5H91eYc3Hjkf3fyOlmrLnHHLxDkhPQA+8Yn9v7k

      1yKlf++efq9jxGIcETT1Y52THdkTfXi1DUpix2mIK1UlSLtKvlQ='
  - secure: ! 'rcA2LagYuEyevxqrqhjCcdMuPfs/ioPQthJ0LtbjS1vYdqgUja81PELUzybe

      O7EkyvbgSgy9Sy9mQnf59G/iP21/hocVNLMrZQiHf5qtjTDxy83ZWPBAhboy

      5mOH0rrR1IDw7CdYWesUIKGTwGLo0I++9m3ucLr83cIpN083D0o='
  - secure: ! 'TglOdszzw3jOBfeVszvwRfNVk6kPOaIXzOmnSeoEJHsg0T2PTlD+zGe4SuL9

      CjgIeVQxechruKfHBesbtTPG/eFkPOlv+ACQAvVxI7jw5UfsMVZ3xFjo4h99

      9x5zR1hjUrR9HSw5E571LtxjDd5I34BqNkq0hey9nU+mybSaLmo='
  - secure: ! 'nAExICFdGnMCZDLtZAN8P6eTXEOo2aV627w4/jaBp+KTxTSljNmPQK0OqNsE

      9k4pysx+4rRTyIDnzxxtW6R5TDG7qZU3tMtwjAYkQFkRF3qWYTtTlzShHtoW

      p9+ueKjFduYKr6by0hbc1Pu5DJe5LP/tCfisnCbKiDxs7qOjRXo='
  - secure: ! 'TGHVOzxVVCNkcqIfmcQ/geWf278FJuRTiApfP3Bd4ZcjwfD8TkvNY+lWC9n8

      hWWcMAw9k2aKpATq+aLnQU7V4L/1enkZf3G9zREXaKTXRDmKuz/DKjofvXt9

      UgbQ/D0QB1/Ft5Xe8HmQ0K30CfFvVONGtbP7a+JoPV3+RL3szCo='
  - secure: ! 'Z+dsI1FnAKeDsO3bsOx3UCk80u05rG9xQevzCSMPZc20Nt7WIJIhDYTBFrhw

      oB1JijBwCabcqLzvPhRQKENO0uNFcx2JM5vfDPHJZ3UOvIUzhUH5Kyz4EpUD

      JbaE9It3PVfQ4YIOPmYgC1sbCHMwSVPi2dvBHW6u1xGk3NvpYLg='
  - secure: ! 'jDWalpDqdL6SCDtl+uAfRhqap+fs5+M5IkkFw+UebvlZ/AWuC4qRAmkZ2Ooa

      FXRZeOjQt6JxwA7PSGtsqC8hCEaY1jchDYJMymgoS/yONKPWsAKJG715OT7q

      JzKEX32TA8hDK8Y+IX2SoCGYg4ETHBW4lVL0foF0eGR8dMIKqdc='
  - secure: ! 'Dv/JBdp/y1VKpP5XaRXnLBbzid6jIL07SRd7TzTOVCoZjjk9apJSlMiYFt/s

      amZ5fSj4C8d5E9I4u8hNYptbth4/09/6X3tT4fDiTV30vzn364F+drTekgtD

      FiyJ9i7M5N5UlokdDnWZQKHDxeothK49f0MdS+cZKWNzcBOxw+I='
  - secure: ! 'O9KmAtna5WtEBNaj30IZf6hfTtxtyKR6vPw7oHW4mMg26w+Pr8nAcs9GyQOQ

      mql5xJAQWajd3LKHhvs+IEfla0akE4v6KnH2PCPfPdfyXwb5EXilm6JSXTOn

      v1tI8drpcC6un71y7zoBtZY9q1f/C2SSCwHP/tDCmnGXc43Qgrw='
  - secure: ! 'gItuY4w+EhM7YlvXcNsl6ARy63vR1deHIH4F0h3nod75d1KYPulHMhdUcpAB

      +vqqCjbUMNKmDsnJWR6Xi45OxtB6i2ahbQe2g+Hm9i1KvKtJ4r02rmFaYzWH

      tH9Jtm6ios+4bFm2DQntfPWpA1tZqpL3cw+L5PTpYCNmXE21rhE='
  - secure: ! 'VjToWJ9KDAFx+/wNAbAd1yqrP/AMMfO6GE6ibqxFkIIIZAumXWSIXiRcuk+I

      guVQmTY3uRtAE3wzZomi6jCoDpNqwOlnxbOH8ctUmeRBWAyiWDH4+zkiiuzC

      6y88aSLnTjcIFGU16fw3dVuPS0UmykLilRjpTZaf9EjWLjgDsis='
  - secure: ! 'HTIOKZffpLbXPtsoIZ6WFKVIzTgQ6Smudu/jEDJBX0HiRRZMFKZrvyJGtdt1

      6Zi/qZONfiGBsuPp4+vmzs8BRUlaB8RMamiB8juGkLXgGqgCSwQFffRvrsV2

      dXuvSB+O+YTDhBNOHXZ/7mRigiqIHzwCNT4fM0hKCBFqhlw44B0='
